# Generated by Django 5.1 on 2024-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.IntegerField(),
        ),
    ]
