# Generated by Django 5.1.2 on 2024-10-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.CharField(
                default="https://images.app.goo.gl/vLoG1zbse4oQ8LQR7", max_length=500
            ),
        ),
    ]
