# Generated by Django 5.1.2 on 2024-10-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.CharField(
                default="https://www.svgrepo.com/show/7059/plate-fork-and-knife.svg",
                max_length=500,
            ),
        ),
    ]
