# Generated by Django 5.1.3 on 2024-12-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Masculine", "Masculine"),
                            ("Feminine", "Feminine"),
                            ("Prefer not to say", "Prefer not to say"),
                        ],
                        default="Prefer not to say",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("contact_name", models.CharField(max_length=50)),
                ("contact_title", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("webpage", models.URLField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("units_in_stock", models.IntegerField()),
                ("units_on_order", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="reporting.category",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="reporting.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "unit_price"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateTimeField()),
                ("required_date", models.DateTimeField()),
                ("shipped_city", models.CharField(max_length=100)),
                ("shipped_name", models.CharField(max_length=100)),
                ("shipped_address", models.CharField(max_length=200)),
                ("shipped_postal_code", models.CharField(max_length=10)),
                ("shipped_country", models.CharField(max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="reporting.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="reporting.product",
                    ),
                ),
            ],
        ),
    ]
