# Generated by Django 5.1.2 on 2024-11-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="image",
            field=models.ImageField(
                default="images/none/default.jpg", upload_to="images/"
            ),
        ),
    ]
