# Generated by Django 5.1.2 on 2024-11-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="addresss",
            new_name="address",
        ),
    ]
