# Generated by Django 5.1 on 2024-08-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
